FROM alpine:3.13.5

RUN apk update --no-cache &&\
    apk upgrade &&\
    apk add --no-cache \
    tzdata \
    bash \
    bash-completion &&\
    echo "" > /root/.ash_history

# change default shell from ash to bash
RUN sed -i -e "s/bin\/ash/bin\/bash/" /etc/passwd

ENV LC_ALL=en_US.UTF-8    
