stages:
  - build
  - dockerhub

build:alpine:
  tags:
    - DOCKER
    - ARM64
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/alpine/Dockerfile --destination $CI_REGISTRY_IMAGE:alpine_$CI_COMMIT_SHA --destination $CI_REGISTRY_IMAGE:alpine_latest 
    
build:ubuntu:
  tags:
    - DOCKER
    - ARM64
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/ubuntu/20.04/Dockerfile --destination $CI_REGISTRY_IMAGE:ubuntu_$CI_COMMIT_SHA --destination $CI_REGISTRY_IMAGE:ubuntu_latest

dockerhub:alpine:
  tags:
    - DOCKER
    - ARM64
  variables:
    GIT_STRATEGY: none
  stage: dockerhub
  only:
    - master
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(echo -n ${dockerhub_user}:${dockerhub_password} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/alpine/Dockerfile --destination $dockerhub_user/base:alpine_$CI_COMMIT_SHA --destination $dockerhub_user/base:alpine_latest --destination $dockerhub_user/base:latest

dockerhub:ubuntu:
  tags:
    - DOCKER
    - ARM64
  variables:
    GIT_STRATEGY: none
  stage: dockerhub
  only:
    - master
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(echo -n ${dockerhub_user}:${dockerhub_password} | base64)\"}}}" > /kaniko/.docker/config.json
    - ls -lah $CI_PROJECT_DIR/ubuntu/20.04
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/ubuntu/20.04/Dockerfile --destination $dockerhub_user/base:ubuntu_$CI_COMMIT_SHA --destination $dockerhub_user/base:ubuntu_latest 


  